In [1]:
import requests
import json
import os
from dotenv import load_dotenv

load_dotenv()
api_key=os.getenv("LLama_API_KEY")


In [2]:
url = "http://127.0.0.1:1337/v1/chat/completions"

payload = json.dumps({
  "model": "Llama-3.2-1B-Instruct.IQ4_XS",
  "messages": [
    {
      "content": "You are a helpful assistant.",
      "role": "system"
    },
    {
      "content": "What is ai",
      "role": "user"
    }
  ]
})
headers = {
  'Authorization': f'Bearer {api_key}',
  'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)

{"choices":[{"finish_reason":"stop","index":0,"message":{"role":"assistant","content":"Artificial Intelligence (AI) refers to the development of computer systems that can perform tasks that typically require human intelligence, such as learning, problem-solving, and decision-making.\n\nAI systems can be categorized into three main types:\n\n1. **Narrow or Weak AI**: This type of AI is designed to perform a specific task, such as image recognition, speech recognition, or playing chess. Narrow AI systems are trained on a specific dataset and can learn from that data to improve their performance.\n2. **General or Strong AI**: This type of AI is designed to perform any intellectual task that a human can. General AI systems are expected to be able to reason, learn, and apply knowledge across a wide range of tasks, similar to how humans do.\n3. **Superintelligence**: This type of AI is significantly more intelligent than current AI systems. Superintelligence is often considered to be a hypot

# LLM Toolbox: Temperature

In [2]:
payload = json.dumps({
  "model": "Llama-3.2-1B-Instruct.IQ4_XS",
  "messages": [
    {
      "content": "You are a witty and sarcastic assistant",
      "role": "system"
    },
    {
      "content": "Write a resignation letter in 1-2 lines",
      "role": "user"
    }
  ],
    "temperature":0.1 #With increased temperature it becomes more creative
})
headers = {
  'Authorization': f'Bearer {api_key}',
  'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)

{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"I am writing to inform you that I have decided to resign from my position as a [insert position] at [insert company name]. After much thought and consideration, I have come to the conclusion that it is in the best interest of both myself and the company to move on.\n\nI have thoroughly enjoyed my time at [insert company name], and I am grateful for the opportunity to have worked with such a talented and dedicated team. However, I feel that it is time for me to pursue new opportunities and explore new challenges.\n\nI would like to thank you for your support and guidance during my time at [insert company name]. I have learned so much from you and I am grateful for the lessons and experiences that I have gained.\n\nI wish you all the best in your future endeavors, and I hope that you will continue to be successful in your work.\n\nSincerely,\n\n[Your Name]","role":"assistant"}}],"created":1754012336,"id":"chatcmpl-ozerGS

In [3]:
payload = json.dumps({
  "model": "Llama-3.2-1B-Instruct.IQ4_XS",
  "messages": [
    {
      "content": "You are a witty and sarcastic assistant",
      "role": "system"
    },
    {
      "content": "Write a resignation letter in 1-2 lines",
      "role": "user"
    }
  ],
    "temperature":1.7 #With increased temperature it becomes more creative, ~1 is optimal value
})
headers = {
  'Authorization': f'Bearer {api_key}',
  'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)

{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Dear HR,\n\nAs of [date of resignation], I have come to the conclusion that my job at [company] is no longer fulfilling me in the way I deserve it to be. Therefore, I kindly ask to be released from my employment agreement with [company] on [date of resignation].\n\nI have made this decision after careful consideration, considering the many opportunities that await me in [insert a statement that expresses your willingness to pursue a different career path], as well as my personal commitments and obligations.\n\nI am leaving [company] with a sincere gratitude for the opportunities, colleagues, and environment provided to me during my time here, and wish all of the best for your continued success.\n\nBest regards,\n\n[Your Name]\n\n[Your Position and Title]","role":"assistant"}}],"created":1754012342,"id":"chatcmpl-OucwunpjX4N1N1xl7fAWb7amF6R0zR52","model":"tinyllama:1b","object":"chat.completion","system_fingerprint":"b1

# LLM Toolbox: Max Token

## Character Tokenization

In [4]:
def character_tockenization(text: str)->list:
    tockens=list(text)
    return tockens

In [5]:
text="Our manager is like brocken clock, he is right twice a day"

In [6]:
character_tockenization(text)

['O',
 'u',
 'r',
 ' ',
 'm',
 'a',
 'n',
 'a',
 'g',
 'e',
 'r',
 ' ',
 'i',
 's',
 ' ',
 'l',
 'i',
 'k',
 'e',
 ' ',
 'b',
 'r',
 'o',
 'c',
 'k',
 'e',
 'n',
 ' ',
 'c',
 'l',
 'o',
 'c',
 'k',
 ',',
 ' ',
 'h',
 'e',
 ' ',
 'i',
 's',
 ' ',
 'r',
 'i',
 'g',
 'h',
 't',
 ' ',
 't',
 'w',
 'i',
 'c',
 'e',
 ' ',
 'a',
 ' ',
 'd',
 'a',
 'y']

## Word Tokenization

In [7]:
text="Dear Sir, I won't be able to attend office, because I threw the laptop in the snoflake lake"

In [8]:
token=text.split(" ")

In [9]:
token

['Dear',
 'Sir,',
 'I',
 "won't",
 'be',
 'able',
 'to',
 'attend',
 'office,',
 'because',
 'I',
 'threw',
 'the',
 'laptop',
 'in',
 'the',
 'snoflake',
 'lake']

## Sub-word Tokenization

In [11]:
from transformers import AutoTokenizer

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.


In [ ]:
# Load tokenizer for BERT (can use RoBERTa, GPT2, etc.)
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [ ]:
text = "Tokenization is interesting because it handles unseen words cleverly."

# Basic tokenization
tokens = tokenizer.tokenize(text)

print(tokens)

## Tokens to IDs

In [ ]:
# Load tokenizer for BERT (can use RoBERTa, GPT2, etc.)
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [ ]:
text = "Happy Bday to me"

# Basic tokenization
tokens = tokenizer.tokenize(text)

print(tokens)

In [ ]:
tocken_to_number=tokenizer.convert_tokens_to_ids(tokens)
print(tocken_to_number)

## Word vectorizations and embeddings

In [69]:
import torch
from transformers import BertModel

In [73]:
token_dog=tokenizer.convert_tokens_to_ids(["dog"])[0]
print("tocken for the word dog is",token_dog)

model=BertModel.from_pretrained("bert-base-uncased")
word_vector_dog=model.embeddings.word_embeddings(torch.tensor([token_dog]))
print(word_vector_dog)

tocken for the word dog is 3899


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tensor([[-1.4935e-02,  1.2444e-02,  9.1277e-03, -1.4333e-02, -2.4053e-02,
         -8.8391e-03, -5.0729e-03,  3.4792e-02,  4.9943e-02, -9.7622e-03,
         -6.7302e-02, -5.5808e-02, -8.4477e-02,  1.1301e-02, -4.0511e-02,
         -9.3478e-02,  2.2908e-02, -3.2941e-02,  1.7266e-03,  1.7777e-02,
         -6.2316e-03, -4.9649e-02, -4.4828e-02, -3.0987e-02,  1.2962e-02,
         -8.1616e-03,  3.4435e-03, -6.5256e-03, -1.5115e-02, -1.0003e-01,
          1.1840e-02, -7.8496e-03, -8.9664e-02,  1.3541e-03, -2.7378e-03,
          2.0956e-02, -4.5374e-02, -2.3927e-02, -5.5758e-02, -1.1604e-02,
          9.9464e-03,  2.5420e-02, -2.0281e-02, -1.8136e-02,  1.3837e-02,
         -1.0506e-02, -3.3592e-03, -2.0255e-02,  7.4511e-02, -6.6017e-02,
          2.9210e-02,  2.0391e-02, -2.9849e-02, -2.0139e-02, -1.2126e-02,
         -3.3120e-02,  4.5548e-02, -1.3883e-02, -4.8897e-02, -5.5070e-02,
         -1.6012e-02,  1.5712e-02, -2.4265e-03,  5.7435e-03, -5.1066e-02,
          2.9750e-02, -4.9678e-02, -1.

In [75]:
word_vector_dog.shape

torch.Size([1, 768])

In [76]:
#This means 768 features has been used to differenciate between different vectors

## Cosine similarity

In [77]:
tocken_dog_id=tokenizer.convert_tokens_to_ids(["dog"])[0]
embedding_dog=model.embeddings.word_embeddings(torch.tensor([tocken_dog_id]))

tocken_wolf_id=tokenizer.convert_tokens_to_ids(["wolf"])[0]
embedding_wolf=model.embeddings.word_embeddings(torch.tensor([tocken_wolf_id]))

tocken_fish_id=tokenizer.convert_tokens_to_ids(["fish"])[0]
embedding_fish=model.embeddings.word_embeddings(torch.tensor([tocken_fish_id]))

In [78]:
cos=torch.nn.CosineSimilarity(dim=1,eps=1e-6)
dog_wolf_similarity=cos(embedding_wolf,embedding_dog)
print(dog_wolf_similarity)

dog_fish_similarity=cos(embedding_fish,embedding_dog)
print(dog_fish_similarity)

tensor([0.3983], grad_fn=<SumBackward1>)
tensor([0.3537], grad_fn=<SumBackward1>)
